In [1]:
# Write a Python program to print the NumPy version in your system.

In [1]:
import numpy as np
print(np.__version__)

1.18.1


In [3]:
# Write a Python program to reverse an array (first element becomes last)

In [4]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
# Write a Python program to convert a list and tuple into arrays.

In [7]:
lst=[1,2,3,4,5,6,7,8]
lst_arr=np.asarray(lst)
lst_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
tpl=(10,20,30,40,50)
tpl_arr=np.asarray(tpl)
print(tpl_arr)

[10 20 30 40 50]


In [9]:
# Write a Python program to find common values between two arrays.

In [10]:
arr_1=np.arange(11,20)
arr_2=np.array([11,15,18])

In [11]:
print(np.intersect1d(arr_1,arr_2))

[11 15 18]


In [12]:
# Write a Python program compare two arrays using numpy.

In [13]:
arr3=np.array((1,2,3,4))
print('Array arr3:',arr3)
arr4=np.array([2,3,5,4])
print('Array arr4:',arr4)
print('arr3>arr4')
print(np.greater(arr3,arr4))
print('arr3>=arr4')
print(np.greater_equal(arr3,arr4))
print('arr3<arr4')
print(np.less(arr3,arr4))
print('arr3<=arr4')
print(np.less_equal(arr3,arr4))

Array arr3: [1 2 3 4]
Array arr4: [2 3 5 4]
arr3>arr4
[False False False False]
arr3>=arr4
[False False False  True]
arr3<arr4
[ True  True  True False]
arr3<=arr4
[ True  True  True  True]


In [14]:
# Write a Python program to change the dimension of an array.

In [15]:
arr_3=np.arange(1,13)
print('arr_3:',arr_3,'Dimension is:', arr_3.ndim)
arr_3.shape=3,4
print('arr_3:',arr_3,'Dimension is:',arr_3.ndim)

arr_3: [ 1  2  3  4  5  6  7  8  9 10 11 12] Dimension is: 1
arr_3: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] Dimension is: 2


In [16]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

In [18]:
a=np.arange(1,100)
b=a[(a%3==0)|(a%5==0)]
print('The multiples of 3 or 5 below 100 are:', b)
print()
print ('Sum is',b.sum())

The multiples of 3 or 5 below 100 are: [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]

Sum is 2318


In [19]:
# Write a Python program to convert a NumPy array into Python list structure.

In [20]:
np_arr=np.arange(0,9).reshape(3,3)
print('Numpy array is')
print(np_arr)
print()
print('List structure is')
print(np_arr.tolist())

Numpy array is
[[0 1 2]
 [3 4 5]
 [6 7 8]]

List structure is
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [21]:
# Write a Python program to how to add an extra column to a numpy array.

In [3]:
arr_p1=np.arange(1,13).reshape(3,4)
print(arr_p1)
print()
arr_p2=np.array([[21],[22],[23]])
print(arr_p2)
print()
arr_new=np.append(arr_p1,arr_p2,axis=1) 
print(arr_new)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[21]
 [22]
 [23]]

[[ 1  2  3  4 21]
 [ 5  6  7  8 22]
 [ 9 10 11 12 23]]


In [ ]:
# Write a Python program to check whether the numpy array is empty or not.

In [4]:
a=np.array([1,2,3,4])
a.size

4

In [5]:
b=np.array([])
b.size

0

In [ ]:
# Write a Python program to normalize a 3x3 random matrix.

In [6]:
print('Random 3X3 matrix is')
r_arr=np.random.random((3,3))
print(r_arr)
print()
r_max,r_min=r_arr.max(),r_arr.min()
print('Max value is:',r_max)
print()
print('Min value is:',r_min)
print()
n_arr=(r_arr-r_min)/(r_max-r_min)
print('Normalized 3X3 matrix is')
print(n_arr)

Random 3X3 matrix is
[[0.40399967 0.41496211 0.43043031]
 [0.21853974 0.96701233 0.22598242]
 [0.82780068 0.51360745 0.59539964]]

Max value is: 0.9670123341000268

Min value is: 0.21853974065104687

Normalized 3X3 matrix is
[[0.24778453 0.26243095 0.2830973 ]
 [0.         1.         0.00994383]
 [0.81400568 0.39422647 0.50350527]]


In [ ]:
# How to swap two rows of an array?

In [7]:
arr5=np.arange(1,16).reshape(3,5)
print('The array is')
print(arr5)
print()
arr5[[0,1],:]=arr5[[1,0],:]
print('The swapped array is')
print(arr5)

The array is
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

The swapped array is
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]]


In [48]:
# Python program to create a random vector of size 10 and sort it.

In [53]:
v=np.random.random(10)
print('The random vector of size 10 is')
print(v)
print()
v.sort()
print('After sort')
print(v)


The random vector of size 10 is
[0.29159128 0.26306452 0.39722874 0.12263229 0.69947237 0.40176978
 0.30586817 0.86290424 0.01429012 0.89216103]

After sort
[0.01429012 0.12263229 0.26306452 0.29159128 0.30586817 0.39722874
 0.40176978 0.69947237 0.86290424 0.89216103]


In [54]:
# Write a Python program to check two random arrays are equal or not.

In [57]:
a=np.random.randint(1,3,5)
print(a)
b=np.random.randint(1,3,5)
print(b)
print()
print(np.allclose(a,b))  # gives false if a and b are not equal

[2 1 1 2 2]
[1 1 2 2 2]

False


In [59]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.

In [62]:
print('Add')
print(np.add(4,8))
print()
print('Subtract')
print(np.subtract(4,8))
print()
print('Multiply')
print(np.multiply(4,8))
print()
print('Divide')
print(np.divide(4,8))



Add
12

Subtract
-4

Multiply
32

Divide
0.5


In [63]:
# Write a Python program to get the dates of yesterday, today and tomorrow

In [64]:
import datetime
today=datetime.date.today()
print("Today's date",today)
yesterday=today-datetime.timedelta(days=1)
print("Yesterday's date",yesterday)
tomorrow=today+datetime.timedelta(days=1)
print("Tomorrow's date",tomorrow)

Today's date 2020-11-26
Yesterday's date 2020-11-25
Tomorrow's date 2020-11-27
